### ISSUE TITLE
The presence of an in-built webhook response should be explained

### ISSUE THREAD

**Issue by ucocodems** [microsoft/Commercial-Marketplace-SaaS-API-Emulator#14]
When executing actions within the emulator that will generate webhook calls, it is not clear that there is an in-built emulation of a webhook implementation receiving events.  This is confusing as the config indicates that there is a URL to a webhook location but without the user deploying their webhook endpoint, calls do not fail and there is no indication that their implementation is not present.

**Comment by scottperham** [comment]
Documentation updated with usage scenarios covering the built-in landing page and webhook
