### ISSUE TITLE
Error hosting emulator container image in App Service

### ISSUE THREAD

**Issue by ucocodems** [microsoft/Commercial-Marketplace-SaaS-API-Emulator#18]
Testing the different Azure hosting options for the emulator: 

Azure Container Instances: works (no TLS, limiting testing options)
Azure Container Apps: Works
Azure App Service: Fails

App Service fails to load a container image of the emulator.  The following error is in the deployment centre logs:

Message: failed to register layer: Error processing tar file(exit status 1): Container ID 1516583083 cannot be mapped to a host ID

Internet searching indicates that this could be an issue with a security layer in the hosting environment and the ID number being too large (https://circleci.com/docs/high-uid-error/).  This might be unique to my environment but recreating a new container image and new App Service didn't resolve this and @scottperham recommended logging for testing.

Repro steps with ACR:
docker build -t marketplaceapiemulator -f docker/Dockerfile .
docker tag marketplaceapiemulator <name>.azurecr.io/marketplaceapiemulator:v1
docker push <name>.azurecr.io/marketplaceapiemulator:v1
Enable Admin User in ACR to light-up deployment options
Select App Service as a deployment option for the container
Review the logs in the App Service deployment centre for errors
Error on browsing to public endpoint

**Comment by mormond** [comment]
I tested this as follows:
- Creating a new App Service plan: plan (B1: 1)
- From ACR > Repositories > Container Image > Select "Deploy to Web App"
- Wait for deployment and browse to URL of new app service
- No errors on deployment
- Worked as expected.

**Comment by azurecloudmatt** [comment]
Tested:
- Cloned the repo
- Build > Push
- From ACR > Repositories > Container Image > Select "Deploy to Web App" - created new app service and plan selecting Linux 
As with above, it's working as expected

**Comment by mormond** [comment]
It looks like this is specific to NPM v9. The image we use in the Dockerfile - node:18-alpine3.16 - has recently been updated to v9. Thus it works for us as we have a cached version of the image. I've been able to repro by removing my local docker image and starting from fresh.

We could either pin to the older version of the image or I can look at possible fixes....

**Comment by mormond** [comment]
See also #21
